[build]
  publish = "."
  command = "node build-config.js"

[[redirects]]
  from = "/inmycontrol"
  to = "/inmycontrol.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/inmycontrol.html"
  status = 200

[[redirects]]
  from = "/course"
  to = "/course.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200
